---
# tasks file for jenkins
- name: Create the jenkins directory
  file:
    path: "{{ jenkins_home_dir }}"
    state: directory
    mode: 0755

- name: Create the jenkins data directory
  file:
    path: "{{ jenkins_data_dir }}"
    state: directory
    mode: 0755

- name: Install Docker composition file
  template:
    src: docker-compose.yml
    dest: "{{ jenkins_home_dir }}/docker-compose.yml"

- name: Set up jenkins systemd service
  block:
    - name: Install systemd service file for foundryvtt-docker
      template:
        src: jenkins.service
        dest: /etc/systemd/system/jenkins.service

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Enable jenkins systemd service to start on boot
      systemd:
        name: jenkins.service
        enabled: true
  when:
    - ansible_service_mgr == "systemd"
