version: "3.8"

volumes:
  data:

services:
  foundry1:
    image: felddy/foundryvtt:latest
    hostname: foundry_docker
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: {{ foundry_data_dir }}
        target: /data
      - type: bind
        source: {{ foundry_cache_dir }}
        target: /cache
    environment:
      - FOUNDRY_PASSWO={{ foundry_password }}
      - FOUNDRY_USERNAME={{ foundry_username }}
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host

